apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: logging-tester
    name: logging-tester
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: logging-tester
    template:
      metadata:
        labels:
          app: logging-tester
      spec:
        containers:
        - image: quay.io/freedomben/volume-tester:latest
          name: logging-tester-container
          imagePullPolicy: Always
